Bug fix:     A bug in the tags components caused the app to be unable to navigate     due to template failure that renders the app useless with the errors:
    Error in nextTick: "TypeError: Cannot read property '__ob__' of undefined"
        &&
    TypeError: Cannot read property '__ob__' of undefined